name: 'Update beta projects from pull requests'
description: 'Updates a beta projects field on issues linked in pull requests'
inputs:
  github-token:
    description: 'Requires an org-level token, that should be defined in secrets. Can be passed in like {{ secrets.ORG_TOKEN }}'
    required: true
  project-field-name:
    description: 'The name of the issues project field to update'
    required: true
  project-field-value:
    description: 'The value to set for the issues project field'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
